name: SmartIR Builder Image Release CI

on:
  push:
    branches:
      - main
    paths:
      - 'docker/ir-cli-builder/**'
permissions:
    contents: write

jobs:
  smartir-builder-docker-release:
    name: Build and release Smart IR builder docker image on linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      # Prerequisite
      - name: Prepare Dockerfile and docker build dependencies
        run: ./docker/ir-cli-builder/docker_build.sh prepare
        shell: bash
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: smartir/smart-ir-builder
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: docker/ir-cli-builder
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}